[package]
name = "nyasniproxy"
version = "0.1.2"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
libc = "0.2"
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
notify = "8"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
rustls-pki-types = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.26"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2"
webpki-roots = "0.26"
